# General Parameters #

debug = true

# Geometry

receivers = "data/input/receivers.txt"
sources = "data/input/sources.txt" 

offset = 5 # [m]

# Model

nx = 100
nz = 100

nb     = 100
factor = 0.009

dh = 10.0

interfaces = []

velocity_interfaces = [1500]

# Seismogram

perc = 99

seismogram_input_path = "data/output/seismogram_water_nt5001_dt0.0004_nrec84.bin"
seismogram_output_path = "data/output/"
save_seismogram = false

nt = 2001
dt = 1.0e-3

# Wavelet

fmax = 30.0
tlag = 0.3

# Snapshots

snap_path = "data/snapshots/"

snap_num  = 50
snap_bool = true




