# ------------------------- General -------------------------
[General]
debug = false
engine = "CPU" # Keys: GPU/CPU

# --------------------------- RTM ---------------------------
[RTM]
save = false

laplacian = true

# ------------------------ Modeling -------------------------
[Modeling]
dh = 10.0

[Modeling.Cerjan]
nb = 100
factor = 0.0015

# ----------------------- Seismogram ------------------------
[Seismogram]
mode = "generate" # Keys: generate/load

[Seismogram.load]
path = ""

[Seismogram.parameters]
nt = 2001
dt = 1e-3

[Seismogram.plot]
perc = 95

# -------------------------- Model --------------------------
[Model]
mode = "create" # Keys: create/load

[Model.load]
nx = 1701
nz = 351
path = "data/input/models/vp_351x1701_10m.bin"

[Model.create]
nx = 200
nz = 100
interfaces = [ 50 ]
layerValues = [ 1500, 2000 ]

# ------------------------- Geometry ------------------------
[Geometry]
mode = "load" # Keys: create/load

[Geometry.load]
save = false

receivers = "data/input/geometry/receivers.txt"
sources = "data/input/geometry/sources7.txt"

[Geometry.create]
offset = 15
receiversDepth = 0

sources = [1700]
sourcesDepth = 8

# ------------------------- Wavelet -------------------------
[Wavelet]
fmax = 30.0
tlag = 0.15

# ------------------------ Snapshots ------------------------
[Snapshots]
numNyquist = true
number = 251
